Update

diff --git a/envinit/envinit b/envinit/envinit
--- a/envinit/envinit
+++ b/envinit/envinit
@@ -1,32 +1,87 @@
 #!/usr/bin/env sh
 
-# macOS
-# On the premise that "Xcode", "Homebrew" are already installed.
-## sudo xcode-select --install
-## /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-if [ "$(uname)" == 'Darwin' ]; then
-
-	# Base install
-	brew install tmux
-	# vim + lua
-	brew install lua
-	brew reinstall vim --with-lua
-	brew install clang-format
-	# pyenv
-	if [ ! -d ~/.pvenv ]; then
-	brew install pyenv
+pyenv_setup(){
+	git clone git://github.com/yyuu/pyenv.git ~/.pyenv > /dev/null 2>&1
 	echo '' >> ~/.bashrc
 	echo '# pyenv' >> ~/.bashrc
 	echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
 	echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
 	echo 'eval "$(pyenv init -)"' >> ~/.bashrc
 	tmp=`pyenv install --list | grep -G "^  [0-9][0-9|\.]*[0-9]$" |sort |tail -1`
-	pyenv install $tmp
-	pyenv global $tmp
-	pyenv rehash
-	sudo easy_install pip
-	sudo pip install pep8 pyflakes
-	sudo pip install pep8 pytest pytest-pep8
+	pyenv install $tmp > /dev/null 2>&1
+	pyenv global $tmp > /dev/null 2>&1
+	pyenv rehash > /dev/null 2>&1
+	return 0;
+}
+
+brew_install () {
+	which $1 > /dev/null 2>&1
+	if [ $? != 0 ]; then
+	echo "$1 will be installed."
+	brew install tmux > /dev/null 2>&1
+	if [ $? != 0 ]; then echo "ERROR: $1 can't be installed."; return 2; fi
+	echo "$1 is installed."
+	else
+	echo "$1 is already installed."
+	return 1
+	fi
+	return 0
+}
+
+yum_install () {
+	which $1 > /dev/null 2>&1
+	if [ $? != 0 ]; then
+	echo "$1 will be installed."
+	sudo yum install $1 -y > /dev/null 2>&1
+	if [ $? != 0 ]; then echo "ERROR: $1 can't be installed."; return 2; fi
+	echo "$1 is installed."
+	else
+	echo "$1 is already installed."
+	return 1
+	fi
+	return 0
+}
+
+apt_install () {
+	which $1 > /dev/null 2>&1
+	if [ $? != 0 ]; then
+	echo "$1 will be installed."
+	sudo apt-get install $1 -y > /dev/null 2>&1
+	if [ $? != 0 ]; then echo "ERROR: $1 can't be installed."; return 2; fi
+	echo "$1 is installed."
+	else
+	echo "$1 is already installed."
+	return 1
+	fi
+	return 0
+}
+
+pip_autoinstall() {
+	sudo pip install pep8 pyflakes pytest pytest-pep8 > /dev/null 2>&1
+}
+
+# macOS
+# On the premise that "Xcode", "Homebrew" are already installed.
+## sudo xcode-select --install
+## /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+if [ "$(uname)" == 'Darwin' ]; then
+
+	# tmux install
+	brew_install tmux
+
+	# vim + lua
+	brew_install lua
+	if [ $? == 0 ]; then brew reinstall vim --with-lua > /dev/null 2>&1; fi
+	brew_install clang-format
+
+	# pyenv
+	if [ ! -d ~/.pyenv ]; then
+	pyenv_setup
+	sudo easy_install pip > /dev/null 2>&1
+	pip_autoinstall
+	echo "Complete python Environment Setup. (pyenv is installed)"
+	else
+	echo "pyenv is already installed."
 	fi
 
 	exit 0
@@ -42,9 +97,9 @@ if [ -f /etc/centos-release ]; then
 
 	# vim + lua
 	#TODO: ./configure --enable-perlinterp
-	which vim >> /dev/null 2>&1
-	if [ $? != 0 ]; then
-	sudo yum install -y lua-devel perl-ExtUtils-Embed > /dev/null 2>&1
+	yum_install lua-devel
+	yum_install perl-ExtUtils-Embed
+
 	mkdir ~/install_tmp
 	cd ~/install_tmp
 	wget ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2 > /dev/null 2>&1
@@ -60,34 +115,39 @@ if [ -f /etc/centos-release ]; then
 
 	# pyenv
 	if [ ! -d ~/.pyenv ]; then
-	cd ~
-	git clone git://github.com/yyuu/pyenv.git ~/.pyenv > /dev/null 2>&1
-	echo '' >> ~/.bashrc
-	echo '#pyenv' >> ~/.bashrc
-	echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
-	echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
-	echo 'eval "$(pyenv init -)"' >> ~/.bashrc
-	source ~/.bashrc
-	tmp=`pyenv install --list | grep -G "^ *[0-9][0-9|\.]*[0-9]$" |sort |tail -1`
-	pyenv install $tmp > /dev/null 2>&1
-	pyenv global $tmp > /dev/null 2>&1
-	pyenv rehash > /dev/null 2>&1
+	pyenv_setup
 	sudo yum install epel-release -y > /dev/null 2>&1
 	sudo yum --enablerepo=epel install python-pip -y > /dev/null 2>&1
 	pip install pip --upgrade > /dev/null 2>&1
-	sudo pip install pep8 pyflakes > /dev/null 2>&1
-	sudo pip install pep8 pytest pytest-pep8 > /dev/null 2>&1
+	pip_autoinstall
 	echo "Complete python Environment Setup. (pyenv is installed)"
+	else
+	echo "pyenv is already installed."
 	fi
 
 	exit 0
 
 # Ubuntu
 elif [ -f /etc/lsb-release ]; then
-	echo ubuntu
-	exit 0
-fi
 
+	# Base install
+	sudo apt-get install git gcc make openssl libssl-dev libbz2-dev libreadline-dev libsqlite3-dev tmux -y
+
+	# vim
+	apt_install vim
+	sudo aptitude install vim-gnome -y
+
+	# pyenv
+	if [ ! -d ~/.pyenv ]; then
+	pyenv_setup
+	apt_install python-pip
+	pip_autoinstall
+	echo "Complete python Environment Setup. (pyenv is installed)"
+	else
+	echo "pyenv is already installed."
+	fi
+
+	exit 0
 # Other (Error)
 else echo "Not Support This OS."; exit 1
 fi
